name: Build
on:
  push:
    branches:
      - master
      - main
      - tmp-*
    tags:
      - v*
  pull_request:

jobs:
  orig_index-just-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]
        os: [macOS-latest, ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - name: Install
        run: |
          python -m pip install --upgrade pip uv
          make venv
      - name: Test
        run: |
          source .venv/bin/activate
          make test

  orig_index:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        os: [macOS-latest, ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          python -m pip install --upgrade pip uv
          make venv
      - name: Test
        run: |
          source .venv/bin/activate
          make test
      - name: Lint
        run: |
          source .venv/bin/activate
          make lint
